spring.application.name=libreria

# Database PostgreSQL
spring.datasource.url=${DB_URI}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}
spring.jpa.hibernate.ddl-auto=update

# Swagger configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=prueba.tecnica.libreria.controller
springdoc.paths-to-match=/**